[package]
name = "bevy_quinnet"
version = "0.2.0-dev"
description = "Bevy plugin for Client/Server multiplayer games using QUIC"
repository = "https://github.com/Henauxg/bevy_quinnet"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["gamedev", "networking", "quic", "bevy", "plugin"]
categories = ["game-development", "network-programming"]
readme = "README.md"

[dependencies]
bevy = { version = "0.8.1", default-features = false, features = [] }
rustls = { version = "0.20.6", default-features = false, features = ["quic","dangerous_configuration"] }
tokio = { version = "1.21.2", features = ["sync", "rt-multi-thread", "macros"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
rcgen = "0.10.0"
quinn = "0.8.5"
futures-util = "0.3.24"
futures = "0.3.24"
bincode = "1.3.3"
serde = "1.0.145"
bytes = "1.2.1"

[dev-dependencies]
rand = "0.8.5"
